# Generated by Django 4.0.4 on 2022-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0004_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
