# Generated by Django 4.0.4 on 2022-06-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0006_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
