# Generated by Django 4.0.4 on 2022-06-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0010_job_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
