# Generated by Django 4.0.4 on 2022-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0013_job_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
