# Generated by Django 4.0.4 on 2022-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0014_alter_job_level_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=650),
        ),
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
