# Generated by Django 4.0.4 on 2022-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0015_alter_job_description_alter_job_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(max_length=1500),
        ),
    ]
