# Generated by Django 4.0.4 on 2022-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0016_alter_job_description_alter_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compensation',
            field=models.TextField(default='None', max_length=1500),
        ),
    ]
