# Generated by Django 4.0.4 on 2022-06-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0018_alter_job_applicants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
