# Generated by Django 4.0.4 on 2022-06-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='field',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
