# Generated by Django 4.0.4 on 2022-06-13 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0021_job_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted',
            field=models.ManyToManyField(blank=True, related_name='accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
