# Generated by Django 4.0.4 on 2022-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobFinderApp', '0022_job_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
